export default {
  volume: 0,
  detune: 0,
  portamento: 0,
  harmonicity: 3,
  oscillator: {
    partialCount: 0,
    partials: [],
    phase: 0,
    type: 'sine',
  },
  envelope: {
    attack: 0.01,
    attackCurve: 'linear',
    decay: 0.2,
    decayCurve: 'exponential',
    release: 0.5,
    releaseCurve: 'exponential',
    sustain: 1,
  },
  modulation: {
    partialCount: 0,
    partials: [],
    phase: 0,
    type: 'square',
  },
  modulationEnvelope: {
    attack: 0.2,
    attackCurve: 'linear',
    decay: 0.01,
    decayCurve: 'exponential',
    release: 0.5,
    releaseCurve: 'exponential',
    sustain: 1,
  },
  modulationIndex: 12.22,
};
